defaults:
  - patch_embed@patch_embed_cfg: conv
  - attention@attention_cfg: gqa
  - block@block_cfg: vanilla
  - _self_

_target_: litevit.models.build_vit
embed_dim: 192
num_heads: 12
depth: 6
num_classes: ${data.num_classes}
dropout: 0.0
drop_path_rate: 0.15
