_target_: litevit.models.build_timm_vit
img_size: ${data.img_size}
patch_size: 4
in_chans: ${data.num_channels}
embed_dim: 128
num_heads: 4
depth: 6
num_classes: ${data.num_classes}
dropout: 0.0
drop_path_rate: 0.0
