# @package _global_

callbacks:
  - _target_: lightning.pytorch.callbacks.LearningRateMonitor
    logging_interval: epoch
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: "val_accuracy"
    mode: max
    save_top_k: 1
    save_last: False
    dirpath: checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}
    filename: best-{epoch}-{val_accuracy:.4f}
  - _target_: lightning.pytorch.callbacks.ModelCheckpoint
    monitor: null
    dirpath: checkpoints/${now:%Y-%m-%d}/${now:%H-%M-%S}
    filename: last-{epoch}


trainer:
  enable_checkpointing: True
