defaults:
  - train_config
  - model: lite_experimental
  - data: mnist
  - loss: cross_entropy
  - optimizer: adam_w
  - scheduler: cosine_warmup
  - metrics: classification
  - trainer: default
  - callbacks: no_checkpoint
  - logger: mlflow
  - _self_

seed: 0
